<a href="https://colab.research.google.com/github/arthurgamaruiz/Projeto-Titanic/blob/main/An%C3%A1liseTitanicParte1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Visualizando a base de treino

In [ ]:
# Importação dos módulos

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

In [ ]:
# Importação dos dados

treino = pd.read_csv("/content/drive/MyDrive/Projeto Titanic/titanic/train.csv")
treino.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# Gera relatório em html
profile = ProfileReport(treino, title="titanic_treino")
profile.to_file("titanic_treino.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 12/12 [00:00<00:00, 65.97it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
# Verificando informações da base
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# Verificando o tipo dos dados
treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [ ]:
# Valores nulos
treino.isnull().sum().sort_values(ascending=False).head()

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

# Visualizando a base de teste

In [ ]:
# Importação dos dados

teste = pd.read_csv("/content/drive/MyDrive/Projeto Titanic/titanic/test.csv")
teste.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
# Verificando informações da base
teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [ ]:
# Verificando o tipo dos dados
treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [ ]:
# Valores nulos
teste.isnull().sum().sort_values(ascending=False).head()

Cabin     327
Age        86
Fare        1
Name        0
Pclass      0
dtype: int64

# Tratamento dos dados

In [ ]:
# Shape da base de treino
treino.shape

(891, 12)

In [ ]:
# Verificando a cardinalidade dos dados
"""
colunas com cardinalidade alta não devem ser utilizadas na modelagem,
pois podem tornar o modelo mais suscetível a erros de generalização.
Eliminar tais colunas
"""
treino.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

In [ ]:
# Eliminando colunas da base de treino
treino = treino.drop(['Name', 'Ticket', 'Cabin'], axis=1)    # axis=1 --> coluna

In [ ]:
# Eliminando colunas da base de teste
teste = teste.drop(['Name', 'Ticket', 'Cabin'], axis=1)

A coluna 'Age' possui valores nulos, então deve ser tratada (substituiremos pela média)

In [ ]:
# Média das idades
treino.Age.mean()  #ou treino['Age'].mean()

np.float64(29.69911764705882)

In [ ]:
# Localizar colunas com valores nulos e substituir pela média
treino.loc[treino.Age.isnull(), 'Age'] = treino.Age.mean()

In [ ]:
# Repetindo para a base de teste
teste.loc[teste.Age.isnull(), 'Age'] = teste.Age.mean()

Para a base de treino, temos dois valores vazios na coluna **Embarked**. Podemos verificar todos os valores nessa coluna e substituir os valores vazios pela **moda**

In [ ]:
# Verificando valores da coluna Embarked
treino.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
# Selecionando a moda dessa coluna
treino.Embarked.mode()[0]

'S'

In [ ]:
# Substituindo os valores vazios
treino.loc[treino.Embarked.isnull(), 'Embarked'] = treino.Embarked.mode()[0]

# Base de teste não possui valores nulos na coluna Embarked

Para finalizar, para a base de teste há um valor vazio na coluna Fare. Vamos substituir pela média

In [ ]:
teste.loc[teste.Fare.isnull(), 'Fare'] = teste.Fare.mean()

Verificando novamente os valores vazios

In [ ]:
# Base de treino
treino.isnull().sum().sort_values(ascending=False).head()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [ ]:
# Base de teste
teste.isnull().sum().sort_values(ascending=False).head()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

Considerando apenas colunas que não são texto

In [ ]:
# Colunas de texto selecionadas
col_treino_nr = treino.columns[treino.dtypes != 'object']
col_treino_nr

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
# Selecionando apenas os valores numéricos da base de treino
treino_nr = treino.loc[:, col_treino_nr]
treino_nr

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
# Para a base de teste
col_teste_nr = teste.columns[teste.dtypes != 'object']
col_teste_nr

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
# Valores numéricos da base de teste
teste_nr = teste.loc[:,col_teste_nr]
teste_nr

PassengerId  Pclass       Age  SibSp  Parch      Fare
0            892       3  34.50000      0      0    7.8292
1            893       3  47.00000      1      0    7.0000
2            894       2  62.00000      0      0    9.6875
3            895       3  27.00000      0      0    8.6625
4            896       3  22.00000      1      1   12.2875
..           ...     ...       ...    ...    ...       ...
413         1305       3  30.27259      0      0    8.0500
414         1306       1  39.00000      0      0  108.9000
415         1307       3  38.50000      0      0    7.2500
416         1308       3  30.27259      0      0    8.0500
417         1309       3  30.27259      1      1   22.3583

[418 rows x 6 columns]

# Selecionar algum modelo para classificar os dados:
- Árvore de classificação: https://scikit-learn.org/stable/modules/tree.html;
- Classificação dos vizinhos mais próximos: https://scikit-learn.org/stable/modules/neighbors.html;
- Regressão Logística: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html.

Antes de utilizar os algoritmos, devemos separar a base de treino em treino e validação

In [ ]:
# Importanto train_test_split
from sklearn.model_selection import train_test_split

In [ ]:
# Separando a base de treino em X e y
X = treino_nr.drop(['PassengerId', "Survived"], axis=1)
y = treino.Survived

In [ ]:
# Separando em treino e validação
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

Árvore de decisão

In [ ]:
# Fazendo a importação
from sklearn import tree

In [ ]:
# Criando o Classifier
clf_ac = tree.DecisionTreeClassifier(random_state=42)

In [ ]:
# Fazendo o ajuste com os dados
clf_ac.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
# Fazendo a previsão
y_pred_ac = clf_ac.predict(X_val)

KNeighboorsClassifier

In [ ]:
# Importação
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Criando o classificador
knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Fazendo o ajuste com os dados
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Fazendo a previsão
y_pred_knn = knn.predict(X_val)

Regressão logística

In [ ]:
# Importando
from sklearn.linear_model import LogisticRegression

In [ ]:
# Criando classificador
clf_rl = LogisticRegression(random_state=42)

In [ ]:
# Fazendo o ajuste com os dados
clf_rl.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [ ]:
# Fazendo a previsão
y_pred_rl = clf_rl.predict(X_val)


# Avaliar os modelos

Para realizar essa análise, podemos utilizar:
- Acurácia:https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html;
- Matriz de confusão: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html.

Avaliando acurácia

In [ ]:
# Importando
from sklearn.metrics import accuracy_score

In [ ]:
# Para a árvore
accuracy_score(y_val, y_pred_ac)

0.6169491525423729

In [ ]:
# Para o knn
accuracy_score(y_val, y_pred_knn)

0.6610169491525424

In [ ]:
# Para a regressão logística
accuracy_score(y_val, y_pred_rl)

0.7254237288135593

Avaliando a matriz de confusão

In [ ]:
# Importando
from sklearn.metrics import confusion_matrix

In [ ]:
# Para a árvore
confusion_matrix(y_val, y_pred_ac)

array([[125,  50],
       [ 63,  57]])

In [ ]:
# Para o knn
confusion_matrix(y_val, y_pred_knn)

array([[133,  42],
       [ 58,  62]])

In [ ]:
# Para a regressão logística
confusion_matrix(y_val, y_pred_rl)

array([[156,  19],
       [ 62,  58]])

Fazendo a previsão para os dados de teste com o melhor modelo (regressão logística)

In [ ]:
# Visualizando X_train
X_train.head()

Pclass        Age  SibSp  Parch     Fare
6         1  54.000000      0      0  51.8625
718       3  29.699118      0      0  15.5000
685       2  25.000000      1      2  41.5792
73        3  26.000000      1      0  14.4542
882       3  22.000000      0      0  10.5167

In [ ]:
# Visualizando a base de teste (apenas com valores numéricos)
teste_nr.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875

In [ ]:
# Eliminando a coluna de id para a base de teste ser igual à de treino
X_teste = teste_nr.drop(['PassengerId'], axis=1)

In [ ]:
# Utilizando regressão logística na base de teste
y_pred = clf_rl.predict(X_teste)

In [ ]:
# Criando uma coluna comm precisão na base de teste
teste['Survived'] = y_pred

In [ ]:
# Selecionando apenas a coluna de Id e Survived para enviar
envio = teste[['PassengerId', 'Survived']]
envio

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
# Exportando para um arquivo csv
envio.to_csv('envio.csv', index=False)    #index=False retira a numeração das linhas